<a href="https://colab.research.google.com/github/AZForest/PyTorchCourse/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

Tue Aug  5 21:12:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [3]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                       ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
TENSOR.ndim

3

In [5]:
TENSOR.shape

torch.Size([1, 3, 3])

In [7]:
TENSOR_2 = torch.tensor([[[1,2,3],
                          [4,5,6]],
                           [[7, 8, 9],
                            [10, 11, 12]
                            ]])
TENSOR_2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [8]:
TENSOR_2.ndim

3

In [9]:
TENSOR_2.shape

torch.Size([2, 2, 3])

In [10]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5588, 0.2297, 0.7390, 0.3385],
        [0.4989, 0.1671, 0.3122, 0.7254],
        [0.7107, 0.4071, 0.0577, 0.7018]])

In [11]:
random_tensor.ndim

2

In [13]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [14]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
zeros.dtype

torch.float32

In [21]:
r = torch.arange(0, end=100, step=6)

In [22]:
zero_r = torch.zeros_like(input=r)
zero_r

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
float_32_tensir = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensir

tensor([3., 6., 9.])

In [1]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
x = torch.rand(1, 3, 4)
x

tensor([[[0.9006, 0.1158, 0.5993, 0.6072],
         [0.5196, 0.6024, 0.2407, 0.2441],
         [0.0019, 0.1507, 0.5196, 0.2203]]])

In [5]:
y = torch.rand(2, 4, 3)
y

tensor([[[0.6306, 0.5823, 0.0155],
         [0.0720, 0.2117, 0.4821],
         [0.8632, 0.5946, 0.1350],
         [0.5483, 0.1555, 0.1139]],

        [[0.5923, 0.1714, 0.6903],
         [0.1017, 0.3209, 0.7770],
         [0.4171, 0.4892, 0.2853],
         [0.4552, 0.1618, 0.5791]]])

In [6]:
y[:, :, 2]

tensor([[0.0155, 0.4821, 0.1350, 0.1139],
        [0.6903, 0.7770, 0.2853, 0.5791]])

In [9]:
z = torch.arange(1, 10).reshape(1, 3, 3)
z

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [10]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [11]:
random_seed = 42
torch.manual_seed(random_seed)
c = torch.rand(3, 3)
torch.manual_seed(random_seed)
d = torch.rand(3, 3)
c, d

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))